runtime: python310   # or python311

entrypoint: gunicorn -b :$PORT main:app

handlers:
  # Serve static files (CSS, JS, images) from /static directory
  - url: /static
    static_dir: static

  # Serve favicon
  - url: /favicon.ico
    static_files: static/favicon.ico
    upload: static/favicon.ico

  # Catch all other routes and send them to Flask
  - url: /.*
    script: auto
